[build]
src = "source"
obj = "target/build"
out = "target"

[build.c]
cstd = "c11"
cppstd = "c++23"
incl = ["include"]

[build.cpp]
cstd = "c11"
cppstd = "c++23"
incl = ["include"]

[game]
exe = "mine"
lang = "cpp"
libs = [ "nwge", "SDL2" ]
