[build]
src = "source"
obj = "target/build"
out = "target"
bip = "3.0+"

[build.c]
include = [ "include" ]
std = "c11"

[build.cpp]
include = [ "include" ]
std = "c++23"

[game]
exe = "mine"
lang = "cpp"
libs = [ "nwge", "SDL2" ]
